### ISSUE TITLE
Unchecked cast causes crash on spectral arrows and some mods

### ISSUE THREAD

**Issue by dvitski** [Arathain/articles-of-temerant#1]
An unchecked cast in an [arrow entity mixin](https://github.com/Arathain/articles-of-temerant/blob/82dfcb377e03bac8f833c747f719d8da38c801fd/src/main/java/net/arathain/aot/mixin/DamageSourceMixin.java#L19) causes a crash with spectral arrows and custom arrows in some mods, such as my own Direbats, because these arrow types extend `PersistentProjectileEntity` and not `ArrowEntity`.
This just needs to check `instanceof ArrowEntity` before casting, of course :)

Original issue: https://github.com/teamhollow/direbats/issues/17

**Comment by Arathain** [comment]
Weird, in my dev environment the spectral arrow worked just fine. Will publish a fix ASAP.

**Comment by varencilator** [comment]
Seems that fixed it!

**Comment by dvitski** [comment]
Nice! :D
